### ISSUE TITLE
Arguments missing on help

### ISSUE THREAD

**Issue by Fastidious** [skeeto/enchive#1]
It seems the `--derive` or `-d` argument is missing from the help (under macOS I could not find it). Could it be added? Is there any other missing? Thanks!

**Comment by skeeto** [comment]
I'm not sure what you mean. Can you describe in more detail what you
expect and what you see instead? If you run this:

    $ enchive help keygen

It should mention --derive in the printout, along with the default.

**Comment by Fastidious** [comment]
Hi @skeeto, I was hoping that `enchive help` would have a mention of it. The ability of using `enchive help keygen` completely escaped me, thanks!

**Comment by sergeevabc** [comment]
Still I do not understand what is ``---derive``.
If we launch ```enchive keygen```, then .pub & .sec are created, the same thing happens with that switch.
The only visual difference is that ```secret key passphrase``` is asked for besides ```passphrase```.

**Comment by skeeto** [comment]
As a hint to what's going on, check out the "fingerprint" command. 
First, I'll generate a fresh key. I'm leaving the protection passphrase 
blank for this example. The protection passphrase is used to encrypt the 
actual key at rest.

    $ enchive keygen -f
    passphrase (empty for none):
    $ enchive fingerprint
    22d04726-1c38f640-c3a2e247-6da02de3

Next I'll generate another new key (-f to overwrite):

    $ enchive keygen -f
    passphrase (empty for none):
    $ enchive fingerprint
    f1e54bcc-6518fdac-1b08ee9c-d879dbf3

Notice the fingerprint is different because it's an entirely new key. 
Both were derived from system entropy.

Next, I'll use --derive, and "cool" for the secret key passphrase. This 
will not use any system entropy. Enchive will take 10 seconds or so to 
complete, since the key derivation process is expensive. Notice there's 
no option to leave it empty ("empty for none") since that wouldn't make 
any sense.

    $ enchive keygen -f --derive
    secret key passphrase: 
    secret key passphrase (repeat):
    passphrase (empty for none):
    $ enchive fingerprint
    8642a9d8-dda1d8b1-31d3137d-7c34b14f

And again, entering "cool" as the passphrase:

    $ enchive keygen -f --derive
    secret key passphrase:
    secret key passphrase (repeat):
    passphrase (empty for none):
    $ enchive fingerprint
    8642a9d8-dda1d8b1-31d3137d-7c34b14f

Notice that it's the same exact key. If you enter "cool" on your own 
machine, you'll generate the same keypair as me. The --derive option is 
a feature to allow you to generate the same key twice, as a way of 
storing the key in your brain. You won't need to back it up. The catch 
is that you need to use a lengthy/strong passphrase for your secret key, 
since anyone with access to any encrypted file could attempt an offline 
crack. It's trading a little bit of security for a lot of flexibility.

**Comment by sergeevabc** [comment]
Ah, now I see! Thank you for a thorough explanation, @skeeto.
