### ISSUE TITLE
enchive-mode: load files in the right mode

### ISSUE THREAD

**Issue by nico202** [skeeto/enchive#13]
Hi, I can load and save enchived files using enchive-mode, but they are all loaded in fundamental.
Is it possible to tell emacs to open them in the right mode?

Thanks, nicolò

**Comment by skeeto** [comment]
Did you "M-x enchive-mode" before visiting encrypted files? It's a 
global minor mode that is disabled by default. Needing to enable it is a 
little awkward, but this is following the principle that loading an 
Emacs package shouldn't necessarily activate it. Activation is an 
explicit step.

It's also entirely dependent on the file extension (".enchive") rather 
than any sort of magic numbers, since Enchive intentionally doesn't have 
a file signature.

**Comment by nico202** [comment]
Yes it's enabled, and visiting .enchive file prompts me for the password and decryption/encryption works. The problem is decrypted files (e.g., private.py.enchive) are in fundamental and not in their mode (python-mode in the example)

**Comment by skeeto** [comment]
Oh, I get what you're saying now. Yup, that's something that needs to be 
fixed, though I can't think off-hand of the correct way to go about it. 
I'll have to research it.

**Comment by skeeto** [comment]
This has been fixed by #15.
