### ISSUE TITLE
usage of urandom

### ISSUE THREAD

**Issue by nico202** [skeeto/enchive#24]
https://github.com/skeeto/enchive/blob/3f1910cb0c7ed30ee09a293ca0a91e2b57486722/src/enchive.c#L723

Yesterday I was reading this: http://insanecoding.blogspot.com/2014/05/a-good-idea-with-bad-usage-devurandom.html

Don't have time to check now your usage, but it might be interesting to read

**Comment by skeeto** [comment]
That article (from 2014) is simply wrong. It's based on old myths and 
superstition. On Linux, /dev/random and /dev/urandom draw from the exact 
same CSPRNG. The only difference is the former blocks due to a misguided 
entropy estimator, a fatal misfeature. Have a look at this article:

https://www.2uo.de/myths-about-urandom/

The official random(7) man page even cites this article:

https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/commit/?id=983c70fcfcbdea3d67bc9e5b7683df01adc31d5b

For a long time random(7) was poorly written and perpetuated the myths. 
Fortunately that was corrected through a series of changes in 2016, such 
as this one:

https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/commit/?id=289b177f0ffb9ac69dace3b0fbecc0757aa0dc58

Here's what random(7) says today:

> Unless you are doing long-term key generation (and most likely not 
> even then), you probably shouldn't be reading from the /dev/random 
> device or employing getrandom(2) with the GRND_RANDOM flag. Instead, 
> either read from the /dev/urandom device or employ getrandom(2) 
> without the GRND_RANDOM flag. The cryptographic algorithms used for 
> the urandom source are quite conservative, and so should be sufficient 
> for all purposes.

The only danger of using /dev/urandom on Linux is that it's very early 
in boot and hasn't been seeded yet (the one and only time it *should* be 
blocking). This is not an issue for Enchive since it will never run 
anywhere near that early.

**Comment by nico202** [comment]
Thanks for the useful information! Sorry to have bothered with an old blog post, but since I'm not keeping updated with those details I just wanted to be sure enchive was safe :) 
Thanks again, closing!
