### ISSUE TITLE
The enchive default extension is a distinguishing mark

### ISSUE THREAD

**Issue by kewlfft** [skeeto/enchive#9]
I find the default `enchive` extension a strong distinguishing mark that seems in contradiction with the design of the tool:
> A purposeful design choice is that encrypted/archived files have no distinguishing marks whatsoever (magic numbers, etc.), making them indistinguishable from random data.

Using something shorter and more generic like `.enc` or `.arc` would make it more neutral, otherwise I see it as a flashing light that makes enchive files very recognizable and therefore more prone to targeted attacks.

This is to have your opinion on the topic as you may see it differently.

**Comment by nico202** [comment]
I, as a user, like the fact that the extension is easily distinguishable.  You can easily rename the file if it's that important to mimic random data, but if in 3 years you find sth.enchive you may have forgotten about enchive, but you are given an easy way to "recover" it. Else I'll probably end up asking "which program was I using to encrypt things?" And the file would get lost. So IMHO it's just safer to have a long extension by default

**Comment by kewlfft** [comment]
I see your point, this will make it easier to recognize for us which is nice indeed but also for someone who could 3 years from now open the archive by just googling the extension if let say a weakness was found in the algorithm.

**Comment by skeeto** [comment]
This is a good observation. The primary goal is that the file format, 
which is not under the user's control, does not betray that it contains 
Enchive-encrypted data. The file extension is purely a UI convenience. 
You're free to name files whatever you like, putting it completely under 
your own control. You can override the UI's default with an explicit 
output filename (or by using stdin/stdout pipes):

    $ enchive archive --delete data.zip data.zip.enc
    $ enchive extract --delete data.zip.enc data.zip

I thought I had already made this a compile-time configuration option, 
but I had not. As of d09debe you can control the automatic file 
extension with ENCHIVE_FILE_EXTENSION at compile-time. For example:

    $ make CFLAGS='-O3 -DENCHIVE_FILE_EXTENSION=.enc'

This build would use ".enc" instead of ".enchive" for the file 
extension, so you could again rely on implicit output filenames.

I personally like keeping the standard extension for my own archives in 
order to keep track of what's what. I still have some ancient GnuPG 
encrypted files around that need to stand apart — which, incidentally, 
requires an old version of GnuPG to decrypt due to key format changes 
over the years, serving as an important lesson for Enchive not to make 
the same mistake.

**Comment by kewlfft** [comment]
Very good, that fully addresses the issue I raised.
